removes update loop and lower joint_server message timeout
PilzDE/pilz_teach pull request #52
Opened 2020-01-17 14:27 UTC by DamKoVosh

No use to do the robot stop ourselfs, if we can use the timeout of the jog server.

2020-01-17 14:29 UTC, DamKoVosh commented
The problem however is, that the jog server currently seems to have a but. Sending one twist will result in every joint jog repeating this twist instead of getting executed itself

2020-01-21 09:36 UTC, tobi-v requested changes

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/scripts/key_teleop.py
> +    rate = rospy.Rate(50)
Replace hard-coded frequency with a meaningful variable name. Otherwise, nobody knows why this value is chosen.

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/scripts/pilz_teleop_driver.py
> +        rospy.sleep(1)
Hardcoded time

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/src/pilz_teleoperation/teleoperation_driver.py
> +    def _send_updated_twist(self, ts):
Recommendation:
`def _send_updated_twist(self, ts):
    self._twist_publisher.publish(self._update_twist(ts))

def _update_twist(ts):
    new_twist = _TeleoperationTwist(...)
    ....
    ts.twist = new_twist
    return ts`

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/src/pilz_teleoperation/teleoperation_driver.py
> +        new_twist = _TeleoperationTwist(linear=ts.twist.linear, angular=ts.twist.angular)
Is it really necessary to create a new _TeleoperationTwist whenever this method is called? I'm not sure about memory management in python, but this looks as if it could contribute to performance issues if the code is executed on a weak CPU.

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/src/pilz_teleoperation/teleoperation_driver.py
> +    def _send_updated_jog(self, js):
- See recommendation on _send_updated_twist
- See the question on necessity of new_twist

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/src/pilz_teleoperation/teleoperation_driver.py
> +        new_jog.copy_jog_data(js)
This method also copies the joint names whenever it is called. Is this necessary?

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/test/integrationtests/test_key_teleop.py
> +    def _publish_object_to_topic_and_assert(self, what, topic):
As this method's name already makes clear: This method does two things. I suggest splitting it up.

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/test/integrationtests/test_key_teleop.py
> +        self._wait_for_event_with_timeout(lambda: self.twist_published, secs=5, msg="driver did not publish")
self.twist_published is also used by the startup_jog test, thus the name obscures the variable's use. I recommend renaming this variable to object_is_published.

2020-01-21 09:36 UTC, tobi-v commented on pilz_teleoperation/test/unittests/param_server_mock.py
> +_package_dir = "/".join(os.path.dirname(os.path.realpath(__file__)).split("/")[:-2])
Suggestion to improve readability: Get path via rospack

2020-05-07 11:39 UTC, tobi-v approved these changes

2020-05-07 11:41 UTC, merged